name: Update files.json

on:
  push:
    paths:
      - 'files/**'
      - '.github/workflows/update-files-json.yml'
      - 'generate-files-json.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run script to generate files.json
        run: node generate-files-json.js

      - name: Commit and push updated files.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/files.json
          git commit -m "chore: auto-update files.json" || echo "No changes to commit"
          git push
