name: Update files.json

on:
  push:
    paths:
      - 'files/**'
      - '.github/workflows/update-files-json.yml'
      - 'generate-files-json.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generate-files-json
        run: node generate-files-json.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/files.json
          git commit -m '🤖 自动更新 files.json' || echo "No changes to commit"
          git push
